name: lightning
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - arrow==1.4.0
      - attrs==25.4.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - codecarbon==3.2.0
      - comet-ml==3.55.0
      - configobj==5.0.9
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - docstring-parser==0.17.0
      - dotenv==0.9.9
      - dulwich==0.25.0
      - everett==3.1.0
      - fief-client==0.20.0
      - filelock==3.20.1
      - fire==0.7.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.27.2
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonargparse==4.44.0
      - jsonnet==0.21.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jwcrypto==1.5.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - medmnist==3.0.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.6.1
      - numpy==2.4.0
      - nvidia-ml-py==13.590.44
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - questionary==2.1.1
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.12.20
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - typer==0.20.1
      - typeshed-client==2.8.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - wrapt==2.0.1
      - wurlitzer==3.1.1
      - yarl==1.22.0
      - yaspin==3.4.0
prefix: /opt/miniconda3/envs/lightning
